.\" Copyright (c) 1993-1997 Matsusita Soft-Research, INC. Akira Takuma
.TH TERMLIB 3 "1997年09月13日"
.SH 名前
termlib \- 端末制御ライブラリ
.SH 形式
.B #include
\fB"\fRtermlib.h\fB"\fR
.LP
int
.B term_init
(int
.I mode
)
.LP
void
.B term_clear_all
(void)
.LP
void
.B term_clear_line
(void)
.LP
void
.B term_clear_end
(void)
.LP
void
.B term_bell
(void)
.LP
void
.B term_locate
(int
.I x
, int
.I y
)
.LP
void
.B term_home
(void)
.LP
void
.B term_insert
(void)
.LP
void
.B term_insert_char
(void)
.LP
void
.B term_up
(void)
.LP
void
.B term_down
(void)
.LP
void
.B term_left
(void)
.LP
void
.B term_right
(void)
.LP
void
.B term_top
(void)
.LP
void
.B term_crlf
(int
.I pos
)
.LP
void
.B term_fill_right
(void)
.LP
void
.B term_attrib
(int
.I attrib
)
.LP
void
.B term_set_raw
(void)
.LP
void
.B term_reset_raw
(void)
.LP
void
.B term_set_cbreak
(void)
.LP
void
.B term_reset_cbreak
(void)
.LP
void
.B term_set_echo
(void)
.LP
void
.B term_reset_echo
(void)
.LP
void
.B term_set_nl
(void)
.LP
void
.B term_reset_nl
(void)
.LP
void
.B term_enable_mouse
(void)
.LP
void
.B term_disable_mouse
(void)
.LP
int	
.B term_system
(char*
.I str
)
.LP
int	
.B term_select
(void)
.SH 機能説明
.B termlib
は端末を制御する処理ルーチンを集めたライブラリです。
.LP
.B term_init
関数はモード
.I mode
(0:初期化,1:一時的に元に戻す,2:再初期化,3:元に戻す)に従って端末を初期化します。
.LP
.B term_clear_all
関数は画面をクリアします。
.LP
.B term_clear_line
関数はカーソル位置の 1 行クリアします。
.LP
.B term_clear_end
関数はカーソル位置から画面右下までクリアします。
.LP
.B term_bell
関数はベルを鳴らします。
.LP
.B term_locate
関数はカーソルを座標
.I x
,
.I y
に移動します。
.LP
.B term_home
関数はカーソルをホーム位置へ移動します。
.LP
.B term_insert
関数はカーソル位置に 1 行空行を挿入します。
.LP
.B term_insert_char
関数はカーソル位置に 1 文字空白を挿入します。
.LP
.B term_up
関数はカーソル位置を 1 行上に移動します。
.LP
.B term_down
関数はカーソル位置を 1 行下に移動します。
.LP
.B term_left
関数はカーソル位置を 1 桁左に移動します。
.LP
.B term_right
関数はカーソル位置を 1 桁右に移動します。
.LP
.B term_top
関数はカーソル位置を行頭に移動します。
.LP
.B term_crlf
関数は改行します。
.LP
.B term_fill_right
関数は右端に空白を挿入します。
.LP
.B term_attrib
関数は属性
.I attrib
に従って表示属性を変更します。
.LP
.B term_set_raw
関数は端末の RAW モードをセットします。
.LP
.B term_reset_raw
関数は端末の RAW モードをリセットします。
.LP
.B term_set_cbreak
関数は端末の CBREAK モードをセットします。
.LP
.B term_reset_cbreak
関数は端末の CBREAK モードをリセットします。
.LP
.B term_set_echo
関数は端末の ECHO モードをセットします。
.LP
.B term_reset_echo
関数は端末の ECHO モードをリセットします。
.LP
.B term_set_nl
関数は端末の NL モードをセットします。
.LP
.B term_reset_nl
関数は端末の NL モードをリセットします。
.LP
.B term_enable_mouse
関数はマウスを有効にします。
.LP
.B term_disable_mouse
関数はマウスを無効にします。
.LP
.B term_system
関数は端末を一時解放し、コマンド
.I str
を実行します。
.LP
.B term_select
関数は端末から入力があるかチェックします。
.SH 戻り値
.B term_init
,
.B term_system
,
.B term_select
関数以外は戻り値を返しません。
.LP
.B term_init
関数は正常終了すれば 0 をエラーの場合は 0 以外を返します。
.LP
.B term_system
関数は system 関数の戻り値を返します。fork に失敗した場合は 127 を返します。
.B term_select
関数はキー入力があれば 0 以外を、なければ 0 を返します。
.SH バグ
信頼性は保証できませんが、このライブラリを使用したプログラム
で現在のところ特に支障は起きていません。
